
[functions.getImageUploadUrl]
enabled = true
verify_jwt = true
import_map = "./functions/getImageUploadUrl/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/getImageUploadUrl/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/getImageUploadUrl/*.html" ]

[functions.deleteImageFromCloudflare]
enabled = true
verify_jwt = true
import_map = "./functions/deleteImageFromCloudflare/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/deleteImageFromCloudflare/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/deleteImageFromCloudflare/*.html" ]

[functions.getVideoUploadUrl]
enabled = true
verify_jwt = true
import_map = "./functions/getVideoUploadUrl/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/getVideoUploadUrl/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/getVideoUploadUrl/*.html" ]

[functions.generate_recommendations]
enabled = true
verify_jwt = true
import_map = "./functions/generate_recommendations/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate_recommendations/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate_recommendations/*.html" ]

[functions.generateRecommendations]
enabled = true
verify_jwt = true
import_map = "./functions/generateRecommendations/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generateRecommendations/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generateRecommendations/*.html" ]

[functions.deleteUser]
enabled = true
verify_jwt = true
import_map = "./functions/deleteUser/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/deleteUser/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/deleteUser/*.html" ]
